import type { Event } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Next.js Mumbai Meetup',
    description: 'Join us for our monthly Next.js meetup. We will have talks on the latest features in Next.js 15, server components, and Vercel hosting.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    location: 'BKC, Mumbai',
    category: 'Meetup',
    urls: ['https://meetup.com/nextjs-mumbai'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'React State Management Workshop',
    description: 'A deep dive into modern React state management libraries like Zustand, Jotai, and Recoil. This is a hands-on workshop, so bring your laptops!',
    event_date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    location: 'Andheri, Mumbai',
    category: 'Workshop',
    urls: ['https://workshop.example.com'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
  {
    id: '3',
    title: 'AI in FinTech Conference',
    description: 'A full-day conference exploring the impact of Artificial Intelligence on the financial technology sector in India.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    location: 'Virtual Event',
    category: 'Conference',
    urls: ['https://conference.example.com'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
  {
    id: '4',
    title: 'Mumbai Tech Hackathon 2024',
    description: 'The biggest hackathon in Mumbai is back! 48 hours of coding, building, and networking. Prizes worth over ₹5,00,000.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    location: 'Powai, Mumbai',
    category: 'Hackathon',
    urls: ['https://hackathon.example.com'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
  {
    id: '5',
    title: 'Tech Talk: The Future of WebAssembly',
    description: 'A tech talk by a Google expert on how WebAssembly is changing web development.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    location: 'Lower Parel, Mumbai',
    category: 'Tech Talk',
    urls: [],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
  {
    id: '6',
    title: 'DevOps & Cloud Native Meetup',
    description: 'Discussing the latest trends in DevOps, Kubernetes, and cloud-native technologies.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 22)).toISOString(),
    location: 'Worli, Mumbai',
    category: 'Meetup',
    urls: ['https://meetup.com/devops-mumbai'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
   {
    id: '7',
    title: 'Advanced TypeScript Workshop',
    description: 'Master advanced TypeScript concepts like conditional types, mapped types, and decorators.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Virtual',
    category: 'Workshop',
    urls: ['https://ts-workshop.example.com'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
   {
    id: '8',
    title: 'Web3 & Blockchain Conference',
    description: 'Exploring the future of decentralized applications and blockchain technology.',
    event_date: new Date(new Date().setDate(new Date().getDate() + 50)).toISOString(),
    location: 'Jio World Centre, Mumbai',
    category: 'Conference',
    urls: ['https://web3conf.example.com'],
    image_url: 'https://placehold.co/600x400.png',
    status: 'upcoming',
  },
];
